// See https://aka.ms/new-console-template for more information
using CSDotNetTranning.ConsoleApp.AdoDotNetExamples;
using CSDotNetTranning.ConsoleApp.DapperExamples;
using CSDotNetTranning.ConsoleApp.EFCoreExamples;
using CSDotNetTranning.ConsoleApp.HttpClientExamples;
using CSDotNetTranning.ConsoleApp.RefitExamples;
using CSDotNetTranning.ConsoleApp.RestClientExamples;
using RestSharp;

//var adoDotNet = new AdoDotNetExample();
//adoDotNet.Edit(11);
//adoDotNet.Create("new","new","new");
//adoDotNet.Update(7,"update","new","new");
//adoDotNet.Delete(8);
//var dapper = new DapperExample();
//dapper.Create("test", "testAuthor", "Content");
//dapper.Edit(6);
//dapper.Update(6, "UpdateTitle", string.Empty, string.Empty);
//dapper.Delete(7);
//var efCore = new EFCoreExample();
//efCore.Create("testTitle","new","newContent");
//efCore.Read();
//efCore.Edit(9);
//efCore.Delete(9);
Console.WriteLine("Press enter when API fully loaded!");
Console.ReadKey();
//var httpclientExample = new HttpClientExamples();
//await httpclientExample.Run();
//var rest = new RestClientExample();
//await rest.Run();
//var refitExp = new RefitExample();
//await refitExp.Run();
//Console.ReadKey();
var efCore = new EFCoreExample();
efCore.BulkCreate(0);